name: Build and Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Run setup
        run: ./.vscode/setup.sh
      - name: Run build
        id: build
        run: ./.vscode/build.sh
      - name: Nightly Release
        if: steps.build.outcome == 'success'
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          name: v${{ steps.build.outputs.version }}
          tag_name: v${{ steps.build.outputs.version }}
          files: "./out/Decky\\ Sunshine.zip"